config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"

  #as a user

  resources :profiles, only: [:show]

  resources :products, only: [:show] do
    collection do
      get :deckend
    end
    member do
      get :show_description
    end

    resource :appreciations, only: [:new, :create]
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]

    resources :products

    resources :matches, only: [:index, :show] do
      resources :messages, only: [:create]
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :name, presence: true
  validates :description, presence: true
  validates :value, presence: true
  validates :value, inclusion: { in: [1, 2, 3] }
  validates :photos, presence: true

  belongs_to :user
  has_many :appreciations, dependent: :destroy
  has_attachments :photos, maximum: 5, accept: [:jpg, :png]
  has_many :matches, through: :appreciations

  def self.pick_product(user)
    # where()
  end
end

app/views/shared/_flashes.html.erb
<div id="flashes">
  <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
  <% end %>
  <% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
  <% end %>
</div>

<% if flash[:match_ids] %>
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" id="mymodal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <!-- style match here -->
      <div class="home-page">
        <h1 class="match-title">
          <% if @matches.count == 1 %>
          You got a match!
          <% else %>
          You got matches!
          <% end %>
        </h1>
      </div>
      <% @matches.each do |match| %>
      <%= render 'account/matches/match', match: match, product: match_product(match), other_product: match_other_product(match) %>
      <% end %>
      <%= link_to root_path do %>
      <button type="button" class="btn btn-default btn-lg">Keep on Bartuuring!</button>
      <% end  %>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
	<%= simple_form_for @appreciation_negative, url: product_appreciations_path(@product.id) do |f| %>
	<%= f.hidden_field :liked %>
	<%= button_tag(type: 'submit', class: "icon-footer grey") do %>
	<i class="fa fa-times"></i>
	<% end %>
	<% end %>
 <%= simple_form_for @appreciation_positive, url: product_appreciations_path(@product.id) do |f| %>
 <%= f.hidden_field :liked %>
 <%= button_tag(type: 'submit', class: "icon-footer green") do %>
 <i class="fa fa-check"></i>
 <% end %>
 <% end %>
</div>