config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"

  #as a user

  resources :profiles, only: [:show]

  resources :products, only: [:show] do
    collection do
      get :deckend
    end
    member do
      get :show_description
    end

    resource :appreciations, only: [:new, :create]
  end

  namespace :account do
    resource :profile, only: [:show, :edit, :update]

    resources :products

    resources :matches, only: [:index, :show] do
      resources :messages, only: [:create]
    end
  end

end

app/views/shared/navbars/_arrow.html.erb
<div class="navbar-wagon">
  <!-- icon on the left side -->
  <%= link_to root_path, class: "navbar-wagon-gray" do %>
    <i class="fa fa-arrow-left icon-big"></i>
    <% end %>

</div>

app/views/shared/navbars/_arrow_chat.html.erb
<div class="navbar-wagon">
  <!-- icon on the left side -->
  <%= link_to root_path, class: "navbar-wagon-gray" do %>
  <i class="fa fa-arrow-left icon-big"></i>
  <% end %>

  <i class="fa fa-comments icon-big center-fa icon-green" aria-hidden="true"></i>

  <div></div>
</div>

app/views/shared/navbars/_arrow_user_product.html.erb
<div class="navbar-wagon">
  <!-- icon on the left side -->
  <%= link_to account_matches_path, class: "navbar-wagon-gray" do %>
    <i class="fa fa-arrow-left icon-big"></i>
    <% end %>

  <div>
    <ul class="list-inline">
      <li>
        <%= cl_image_tag @other_user.picture, class: "avatar", height: 40, width: 40, crop: "pad"  %>
      </li>
      <li>
        <h5><%= @other_user.first_name %> <%= @other_user.last_name[0,1] %>.</h5>
      </li>
    </ul>
  </div>

  <div class="navbar-wagon-right">
    <%= link_to show_description_product_path(@other_product), class: "navbar-wagon-item navbar-wagon-link" do %>
    <%= cl_image_tag @other_product.photos.first.path, class:"avatar-square" %>
    <% end %>
  </div>
</div>
</div>

app/views/shared/navbars/_menu_chat.html.erb
<div class="navbar-wagon">
  <!-- icon on the left side -->
  <%= link_to "#", class: "navbar-wagon-gray" do %>
    <i class="fa fa-bars"></i>
    <% end %>

  <div class="navbar-wagon-right">
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-comment"></i>
      <div class="badge badge-green">3</div>
    </div>
    <% end %>

  </div>
</div>

app/views/shared/navbars/_profile_arrows.html.erb
<div class="navbar-wagon">

  <%= link_to account_profile_path, class: "navbar-wagon-gray" do %>
  <i class="fa fa-user icon-big" aria-hidden="true"></i>
  <% end %>

  <div></div>

  <%= link_to root_path, class: "navbar-wagon-gray" do %>
  <i class="fa fa-exchange icon-big" aria-hidden="true"></i>
  <% end %>

</div>

app/views/shared/navbars/_profile_icon.html.erb
<div class="navbar-wagon">

  <%= link_to account_profile_path, class: "navbar-wagon-gray" do %>
    <i class="fa fa-user icon-big" aria-hidden="true"></i>
    <% end %>

  <h2 class="logo-small">üü</h2>

  <div></div>

</div>

app/views/shared/navbars/_profile_logo.html.erb
<div class="navbar-wagon">

  <%= link_to account_profile_path, class: "navbar-wagon-gray" do %>
    <i class="fa fa-user icon-big" aria-hidden="true"></i>
    <% end %>

  <h2 class="logo-small">üü</h2>

  <div></div>

</div>

app/views/shared/navbars/_profile_logo_chat.html.erb
<div class="navbar-wagon">
  <!-- icon on the left side -->
  <%= link_to account_profile_path, class: "navbar-wagon-gray" do %>
    <i class="fa fa-user icon-big" aria-hidden="true"></i>
    <% end %>

    <h2 class="logo-small">üü</h2>

  <div class="navbar-wagon-right">
    <%= link_to account_matches_path, class: "navbar-wagon-item navbar-wagon-link" do %>
    <div class="badge-container">
      <i class="fa fa-comment icon-big">
          <div class="badge badge-green"></div>
      </i>
    </div>
    <% end %>

  </div>
</div>